lsst-sqre/qserv-kafka

- pyproject.toml
Add `Private :: Do Not Upload` to the classifiers so that PyPI will reject this package if it is accidentally uploaded. This a service and the intended release artifact is a Docker container.
> DM-49755: Add do-not-upload classifier

- pyproject.toml
- scripts/install-base-packages.sh
- scripts/install-dependency-packages.sh
Stop cleaning up after apt-get, since we now use a cache file system for its data files. Don't re-run apt-get update when installing dependency packages, since we should continue to use the data cached when updating the base packages.
> DM-49755: Clean up unnecessary apt-get invocations

- pyproject.toml
- src/qservkafka/config.py
- src/qservkafka/dependencies/context.py
- src/qservkafka/exceptions.py
- src/qservkafka/factory.py
- src/qservkafka/handlers/kafka.py
- src/qservkafka/main.py
- src/qservkafka/models/kafka.py
- src/qservkafka/models/qserv.py
- src/qservkafka/services/query.py
- src/qservkafka/storage/rest.py
- tests/conftest.py
- tests/data/jobs/simple.json
- tests/data/status/simple-started.json
- tests/handlers/kafka_test.py
- tests/services/query_test.py
- tests/support/data.py
- tests/support/qserv.py
- tox.ini
- uv.lock
Add a storage backend for talking to the Qserv REST API and a service layer that understands how to process job run requests. Start a query on receipt of a Kafka message and immediately retrieve and report the status of that query, which is published on the job status topic in Kafka.
> DM-49755: Add support for starting jobs

- src/qservkafka/models/kafka.py
- src/qservkafka/services/query.py
- tests/models/kafka_test.py
- tests/services/query_test.py
- tests/support/data.py
When sending an error response because of a low-level protocol error talking to Qserv, do not include query info in the message rather than including fake query info. By definition we were unable to contact Qserv to get actual information, and the schema allows this element to be omitted.
> DM-49755: Do not include query info in error messages

- src/qservkafka/models/kafka.py
- src/qservkafka/models/qserv.py
- src/qservkafka/models/votable.py
- tests/data/jobs/simple.json
- tests/models/kafka_test.py
Include the column type information in the `JobRun` model, which will be used for output serialization. Rework how the output format is represented to match recent changes in SQR-097. Include the `resultLocation` attribute in the `JobRun` model so that it can be included in the output for a completed job.
> DM-49755: Update Kafka models for recent changes

- src/qservkafka/factory.py
- src/qservkafka/models/state.py
- src/qservkafka/services/query.py
- src/qservkafka/storage/state.py
For now, only track query state in memory. This will be used when polling Qserv for current running queries so that we know when queries have finished and what query results to retrieve.
> DM-49755: Start tracking query state

- src/qservkafka/factory.py
- src/qservkafka/storage/rest.py
Log all replies that we get from the Qserv REST API at debug level. This will be useful once we start integration testing.
> DM-49755: Log reply from Qserv REST API at debug level

- .pre-commit-config.yaml
- pyproject.toml
- src/qservkafka/background.py
- src/qservkafka/config.py
- src/qservkafka/dependencies/context.py
- src/qservkafka/factory.py
- src/qservkafka/handlers/kafka.py
- src/qservkafka/main.py
- src/qservkafka/models/kafka.py
- src/qservkafka/models/state.py
- src/qservkafka/services/monitor.py
- src/qservkafka/services/query.py
- src/qservkafka/storage/qserv.py
- src/qservkafka/storage/state.py
- tests/conftest.py
- tests/handlers/kafka_test.py
- tests/support/qserv.py
- tox.ini
- uv.lock
Poll Qserv for state via the MySQL API, every second by default, and look for any queries with status updates or that are missing from the output (which will be the case if the query has finished). Get the metadata for those queries and send Kafka messages recording the updated status. This includes handling for aborted and completed jobs, but the message for completed jobs does not yet include anything about the result of the query.
> DM-49755: Add state polling and job status updates

- Dockerfile
Fix the PATH used by the Docker start command so that the virtual environment is on the PATH.
> DM-49993: Fix Docker start command path

- src/qservkafka/storage/qserv.py
This will make sure that we see heartbeats when running in DEBUG mode, ensuring that the background status checks are working.
> DM-49993: Add debug log when listing running processes

- src/qservkafka/storage/qserv.py
Qserv really does appear to return the columns of the process list query in all uppercase, and then accessing them by lowercase attribute name fails. Rename them in the query, since making them uppercase in the mock creates a cascade of other problems.
> DM-49993: Lowercase the columns from processlist

- .pre-commit-config.yaml
- pyproject.toml
- uv.lock
Remove dependencies from the dev dependency group that are handled by the primary dependencies or by other dependency groups. Update Python and pre-commit dependencies.
> DM-50042: Remove unneeded dev dependencies

- pyproject.toml
- src/qservkafka/config.py
- src/qservkafka/factory.py
- uv.lock
Configure a TLS context for MySQL connections and pass it as an additional connection argument to asyncmy. Disable certificate verification because Qserv uses a self-signed certificate.
Use the unreleased version of Safir for now until `connect_args` support has been merged.
> DM-50095: Add TLS configuration for MySQL connections

- src/qservkafka/services/query.py
- tests/data/jobs/arraysize.json
- tests/services/query_test.py
The `BINARY2` encoder only supports arraysize for char fields. Reject jobs with an immediate error if arraysize is used for any other primitive VOTable type.
> DM-50188: Reject job requests using arraysize

- src/qservkafka/factory.py
- src/qservkafka/handlers/kafka.py
- src/qservkafka/kafkarouters.py
- src/qservkafka/main.py
When the Kafka router was moved into the factory so that it could be used by background tasks, this cased the Kafka handler module to never be imported, so no handler functions were ever registered. Use the same pattern as Ook and move the Kafka router into its own module to avoid circular dependencies.
> DM-50277: Move Kafka router into a separate module

- src/qservkafka/models/qserv.py
A validation alias was not set up for `queryId`.
> DM-50277: Fix parsing of Qserv submit response

- src/qservkafka/factory.py
Use a longer timeout, since the httpx default is very aggressive and seems to often fail.
> DM-50277: Use 30s timeout for Qserv HTTP requests

- scripts/install-base-packages.sh
- scripts/install-dependency-packages.sh
Move the installation of git to dependency packages, since it's only required when installing the package source. Install curl, mysql-client, and netcat-traditional in the container so that more debugging tools are available.
> DM-50277: Update package installations

- Dockerfile
I noticed this discrepancy in the root directories for the uv caches. I'm not sure it'll make a huge difference, but wanted to clarify before we roll this into templates.
> Change cache target to /root/.cache/uv

- src/qservkafka/background.py
- src/qservkafka/config.py
- src/qservkafka/exceptions.py
- src/qservkafka/models/kafka.py
- src/qservkafka/services/monitor.py
- src/qservkafka/services/query.py
- src/qservkafka/storage/qserv.py
- src/qservkafka/storage/state.py
Use the aiojobs scheduler to handle completed jobs as background tasks, allowing us to manage multiple job completions in parallel up to the aiojobs queue (100) and the httpx and SQLAlchemy connection pools (smaller than that). Add a new configuration setting for how long to wait to shut down result processing when terminating the application, and wait for jobs to complete for that long before shutting down gracefully.
Improve error handling of SQL failures, fixing a bug that was seen during testing when the results table for a query wasn't found for some reason.
> DM-50391: Process multiple completed jobs simultaneously

- src/qservkafka/config.py
- src/qservkafka/factory.py
- src/qservkafka/handlers/kafka.py
- src/qservkafka/models/kafka.py
- src/qservkafka/services/query.py
- src/qservkafka/storage/qserv.py
- tests/data/status/simple-aborted.json
- tests/handlers/kafka_test.py
- tests/support/qserv.py
Also listen to the Kafka queue for job cancellation messages, and use the Qserv REST API to cancel the job and immediately retrieve its new status.
> DM-50410: Add support for job cancellation

- pyproject.toml
- src/qservkafka/models/votable.py
Add a serializer that's parallel to the validator for `VOTableArraySize`. This is not strictly needed since the bridge was happy with the `dict` serialization, but it makes Pydantic warnings due to a pydantic-core bug go away and they're annoying in the logs.
> DM-50410: Add serialization for VOTableArraySize

- src/qservkafka/models/votable.py
- src/qservkafka/storage/votable.py
- tests/models/votable_test.py
Move more of the encoding logic to the primitive data type definition instead of encoding it all directly in the VOTable encoder. This makes the code a little bit less complex.
> DM-50410: Refactor BINARY2 encoding

- src/qservkafka/factory.py
- src/qservkafka/models/kafka.py
- src/qservkafka/models/votable.py
- src/qservkafka/services/monitor.py
- src/qservkafka/services/query.py
- tests/services/query_test.py
Previously, there was a lot of duplicate code between the query monitor and the query service, since the query service also had to process job status updates and generate an appropriate Kafka message. Unify that code in the query service and have the query monitor use the query service to process status updates.
> DM-50410: Refactor query service layer

- .pre-commit-config.yaml
- pyproject.toml
- uv.lock
Remove the rules to use the Git version of Safir now that the version with MySQL support has been released.
> DM-50095: Switch to released version of Safir

- src/qservkafka/background.py
- src/qservkafka/config.py
- src/qservkafka/services/query.py
`shutdown_timeout` is really `result_timeout`; it's just also used during shutdown. Rename it to a more accurate name.
> DM-50410: Rename shutdown_timeout to result_timeout

- src/qservkafka/config.py
- src/qservkafka/factory.py
- src/qservkafka/models/qserv.py
- tests/data/status/data-completed.json
- tests/services/query_test.py
- tests/support/qserv.py
Add a test for immediate completion of the job during creation, and add a test for SQL failures when attempting to read the results of the job.
> DM-50410: Add tests for immediate completion

- pyproject.toml
- src/qservkafka/factory.py
Delete some more dead code, call a method that otherwise isn't used, and ignore `RuntimeError` for coverage purposes since I use that like an assertion.
> DM-50410: Further improve test coverage

- src/qservkafka/dependencies/context.py
- src/qservkafka/factory.py
- src/qservkafka/handlers/kafka.py
- tests/handlers/kafka_test.py
Stop rebinding the logger in the Kafka handlers, since the service layer already does this (and has to, for proper logging when called by the background monitor), and remove the code for rebinding loggers since it's now dead.
> DM-50481: Remove some unused code

- src/qservkafka/factory.py
- src/qservkafka/services/query.py
- tests/handlers/kafka_test.py
- tests/handlers/shutdown_test.py
- tests/services/query_test.py
Add tests for proper Redis contents after all tests that track query state, and fix a bug in state handling after aborting a query.
> DM-50481: Fix state management after aborting a query

- changelog.d/20250505_155326_rra_DM_50527a.md
- src/qservkafka/services/query.py
After we finish processing and uploading rows, log how long it took to perform that step.
> DM-50527: Log elapsed time of result processing

- src/qservkafka/dependencies/context.py
- src/qservkafka/factory.py
- src/qservkafka/handlers/kafka.py
- src/qservkafka/main.py
- src/qservkafka/services/monitor.py
- src/qservkafka/services/query.py
- src/qservkafka/services/results.py
- src/qservkafka/storage/state.py
- tests/conftest.py
Extract the background processing from the process context, since we will need to have a process context for workers that doesn't also do background processing. Separate results processing into its own service, used by both the query service and the query monitor, so that result processing workers will be able to use it directly.
> DM-50728: Refactor in preparation for shifting work to arq

- src/qservkafka/background.py
- src/qservkafka/models/state.py
- src/qservkafka/services/monitor.py
Set a default value for the `result_queued` field in the stored query information in Redis, since older entries may not have this value set.
> DM-50728: Set default for new result_queued parameter

- src/qservkafka/constants.py
- src/qservkafka/workers/main.py
Use the Qserv Kafka bridge configuration option for specifying a result processing timeout as a job timeout in the arq configuration.
> DM-50728: Configure an arq job timeout

- changelog.d/20250508_174532_rra_DM_50728.md
- src/qservkafka/constants.py
- src/qservkafka/storage/state.py
Various bugs and other issues may result in stranding a query in Redis with the flag set to indicate it has been dispatched by arq but without any active arq job processing it. As a last resort, tell Redis to forget about these queries after this interval. This will strand unretrieved results in Qserv that will have to be pruned by Qserv garbage collection.
> DM-50728: Add a maximum lifetime for Redis query objects

- src/qservkafka/config.py
- src/qservkafka/services/monitor.py
- src/qservkafka/services/results.py
- src/qservkafka/storage/votable.py
- src/qservkafka/workers/main.py
If the background query status monitor found a still-executing query and then, when it went to send a status update, found that the query had completed before sending the response, it would process the results but still remember the query. The next pass through the monitor would then find the completed query and dispatch it to arq, which would fail because the results had already been deleted.
Fix this by only sending executing updates from the monitor loop and doing so without retrieving the status again.
> DM-50728: Fix duplicate result processing bug in monitor

- src/qservkafka/constants.py
- src/qservkafka/storage/votable.py
- tests/handlers/shutdown_test.py
Try buffering the output of query result encoding in 64KB chunks to see if this improves performance of result processing.
> DM-50728: Buffer uploads of query results

- changelog.d/20250512_155207_rra_DM_50728.md
- src/qservkafka/storage/votable.py
Simplify the BINARY2 encoder to use a smaller stack of async generators and to encode directly into a `BytesIO` object (with an intermediate `bytes` object per row). Batch base64-encoding as well and only encode once we can generate `UPLOAD_BUFFER_SIZE` encoded data (roughly), and use a `memoryview` on the underlying `BytesIO` to avoid needing to make a copy.
Hopefully this will improve performance by decreasing the amount of small garbage generated and reducing the number of memory copies.
> DM-50728: Reduce garbage and copies in BINARY2 encoder

- changelog.d/20250516_165313_rra_DM_50961.md
- src/qservkafka/storage/qserv.py
Fix several places where a database session was opened outside of a try/catch block, thus causing any resulting exception to be thrown uncaught. This in turn led to the worker failing without sending an error response to the TAP server and without removing the query from Redis.
> DM-50961: Fix uncaught SQL exceptions

- pyproject.toml
arq 0.26 added an upper version bound on some dependencies. Ensure at least that version is installed to prevent uv from downgrading arq in order to upgrade other dependencies that may not work properly with arq.
> DM-50964: Bump minimum version of arq

- pyproject.toml
- src/qservkafka/factory.py
- tests/services/query_test.py
- uv.lock
Use the same Kafka broker for publishing metrics events as is used for other Kafka traffic, rather than opening a separate connection. This requires the new Safir support for passing an existing Kafka broker and Kafka admin client into the event manager creation method.
> DM-50964: Share Kafka broker with the event manager

- src/qservkafka/storage/votable.py
Ensure that the `BytesIO` object used to encode results in `BINARY2` is always explicitly closed. This probably makes no difference since it should be garbage-collected anyway, but it feels more correct.
> DM-51004: Explicitly close BytesIO used in VOTable encoding

- pyproject.toml
- uv.lock
Remove pytest-memray, since it didn't work properly. Add pytest-sugar because I prefer its output formatting.
> DM-50964: Update test support libraries

- pyproject.toml
- src/qservkafka/factory.py
- uv.lock
Update the integration with Safir support for metrics events to stop managing the Kafka admin client and instead let the Safir support code manage it.
> DM-50964: Stop managing EventManager admin client

- changelog.d/20250528_154741_rra_DM_51121.md
- src/qservkafka/storage/qserv.py
Explicitly configure the streaming query results to retrieve 100 rows at a time. (This should be made configurable later.) Add another `try` block to ensure that the results are closed before attempting to roll back a transaction, which will hopefully fix SQLAlchemy exceptions about invalid packet sequences.
> DM-51121: Rework how result rows are iterated

- changelog.d/20250528_161854_rra_DM_51121.md
- src/qservkafka/models/qserv.py
Qserv has started sometimes returning `None` for the completed chunks value. Treat that the same as 0.
> DM-51121: Allow completed chunks to be None

- .pre-commit-config.yaml
- changelog.d/20250527_170724_rra_DM_51121.md
- pyproject.toml
- src/qservkafka/config.py
- src/qservkafka/events.py
- src/qservkafka/exceptions.py
- src/qservkafka/models/kafka.py
- src/qservkafka/models/qserv.py
- src/qservkafka/services/query.py
- src/qservkafka/services/results.py
- src/qservkafka/storage/qserv.py
- tests/data/jobs/upload.json
- tests/data/status/upload-started.json
- tests/handlers/kafka_test.py
- tests/support/data.py
- tests/support/qserv.py
- uv.lock
Support table upload requests in the query and upload the table to Qserv before starting the query. Table uploads are done entirely in the frontend at present. The uploaded table and its schema are read into memory, not streamed, due to limitations in the httpx library, and no attempt is currently made to delete the table after the query is complete.
> DM-51121: Add table upload support

- changelog.d/20250609_081648_rra_DM_51308.md
- src/qservkafka/storage/qserv.py
Expect the new Qserv API version 41. This is safe without any further changes. Support for new API features will be added in subsequent requests.
> DM-51308: Bump Qserv API to 41

- changelog.d/20250609_104115_rra_DM_51308.md
- src/qservkafka/services/results.py
- src/qservkafka/storage/qserv.py
- tests/services/query_test.py
- tests/support/qserv.py
The new Qserv version 41 API does not automatically delete results once they have been retrieved and has a new HTTP REST API for deleting results. Use that API to delete results only after they have been successfully retrieved.
> DM-51308: Explicitly delete results from Qserv

- tests/conftest.py
- tests/handlers/kafka_test.py
- tests/kafka/query_test.py
- tests/services/leak_test.py
- tests/services/query_errors_test.py
- tests/services/query_test.py
Change the default parametrization of the Qserv mock to only run in normal mode, and instead parametrize for flaky mode only in the service tests. This should still cover the same error handling, but avoids adding delays to delay-sensitive tests via the Kafka handler that depend on background timing delays.
> DM-51310: Improve testing with flaky Qserv mock

- changelog.d/20250610_181601_rra_DM_51310.md
- src/qservkafka/events.py
- src/qservkafka/models/votable.py
- src/qservkafka/services/results.py
- src/qservkafka/storage/qserv.py
- tests/conftest.py
- tests/support/qserv.py
Add retry logic for SQL calls to Qserv, similar to the retry logic for HTTP requests. Add special handling for result retrieval and uploading, since the entire operation needs to be retried together rather than retrying the individual underlying calls.
> DM-51310: Add retries for SQL failures

- changelog.d/20250612_170316_rra_DM_51364.md
- src/qservkafka/events.py
- src/qservkafka/services/results.py
- src/qservkafka/storage/qserv.py
Rather than reporting one metric for a Qserv API call that eventually succeeds, containing the count of retries, report a separate metrics event for each failure to contact the Qserv API that may be due to SQL or HTTP protocol issues.
Fix the retry logic in the SQL query that gets the current list of running queries from Qserv.
> DM-51364: Improve reporting of Qserv API failures

- changelog.d/20250613_110101_rra_DM_51364.md
- src/qservkafka/config.py
- src/qservkafka/storage/qserv.py
- tests/services/query_test.py
- tests/support/qserv.py
Optionally support sending HTTP Basic Authentication for the Qserv REST API.
> DM-51364: Support HTTP Basic Auth for Qserv REST API

- changelog.d/20250616_170032_rra_DM_51365.md
- src/qservkafka/storage/qserv.py
- tests/support/qserv.py
When sending the API version to Qserv's REST API, always send it as a query parameter and never in the request body. The Qserv version 43 API supports this and it's simpler and more consistent.
> DM-51365: Send Qserv API version as a query parameter

- .pre-commit-config.yaml
- uv.lock
Check that `uv.lock` is in sync with `pyproject.toml` in pre-commit. Update Python dependencies.
> DM-51448: Add uv-lock pre-commit check

- tests/storage/qserv_test.py
- tests/support/qserv.py
Add a test verifying that the Qserv SQL call to get the status of running queries is retried on failure. Adjust the Qserv mock to set the last update time in the query status after query creation.
> DM-51448: Add test for retries of query status

- changelog.d/20250618_140009_rra_DM_51450.md
- src/qservkafka/services/results.py
- src/qservkafka/storage/qserv.py
- tests/data/jobs/upload.json
- tests/data/status/upload-completed.json
- tests/handlers/kafka_test.py
- tests/services/query_test.py
- tests/support/qserv.py
When uploading a temporary table for a query, delete the table from Qserv after the query completes (either successfully or unsuccessfully).
> DM-51450: Delete temporary tables after query completion

- src/qservkafka/factory.py
- src/qservkafka/workers/functions/results.py
- tests/handlers/kafka_test.py
- tests/services/errors_test.py
- tests/services/leak_test.py
- tests/services/query_test.py
Now that query state is stored in Redis, we no longer need a global singleton query state store. Move it into the factory and create it on the fly when needed.
> DM-51448: Move the query state store out of process context

- tests/data/status/data-started.json
- tests/kafka/query_test.py
Test the intermediate status response after the job was started, and avoid one artificial delay by blocking on Kafka messages instead.
> DM-51448: Improve check against real Kafka

- src/qservkafka/services/monitor.py
- tests/services/monitor_test.py
Refactor the query status monitor code to make it easier to test and verify that completed queries aren't dispatched to the arq queue more than once.
> DM-51448: Test that finished queries aren't dispatched twice

- tests/kafka/conftest.py
- tests/kafka/query_test.py
- tests/support/qserv.py
If a query goes missing from the process list but still returns an executing status, we want to ensure that it's not forgotten and is still checked on each pass through the query monitor loop. Add a new test to verify that this is handled properly by the result worker.
> DM-51448: Test handling of queries missing from process list

- changelog.d/20250627_123645_rra_DM_51594.md
- pyproject.toml
- src/qservkafka/models/kafka.py
- src/qservkafka/models/state.py
- src/qservkafka/services/monitor.py
- src/qservkafka/services/query.py
- src/qservkafka/services/results.py
- src/qservkafka/storage/state.py
- src/qservkafka/workers/functions/results.py
- tests/handlers/kafka_test.py
- tests/services/errors_test.py
- tests/services/query_test.py
Fix query start and end times in status responses. Previously, the start time and, for canceled or completed queries, the end time were taken directly from the Qserv query information. This includes only time spent by Qserv, which results in an inaccurate picture of the query execution time in the TAP UWS table. Instead measure query timings from the time the query was received by the bridge to when it completes uploading of the results, or is aware of a failure.
> DM-51594: Fix timings in query status

- tests/handlers/kafka_test.py
- tests/kafka/query_test.py
- tests/services/errors_test.py
- tests/services/leak_test.py
- tests/services/monitor_test.py
- tests/services/query_test.py
- tests/storage/qserv_test.py
- tests/support/data.py
- tests/support/qserv.py
Assume the correct path prefix when loading test data and remove the explicit path prefixes from all of the calls in individual tests. Add a new function for loading the job run message as JSON for use when posting a Kafka message (possibly mocked).
> DM-51603: Simplify test data utility functions

- src/qservkafka/services/results.py
- tests/data/status/simple-failed.json
- tests/data/status/simple-partial.json
- tests/handlers/kafka_test.py
- tests/kafka/query_test.py
Start the process of slowly moving all full end-to-end tests to use a real Kafka instead of fighting with mocks and their limitations by moving the basic success and failure tests into that framework.
> DM-51603: Move more tests into real Kafka tests

- .github/workflows/ci.yaml
- .github/workflows/periodic-ci.yaml
- .pre-commit-config.yaml
- Dockerfile
- changelog.d/20250718_164504_rra_DM_51818.md
- pyproject.toml
- src/qservkafka/background.py
- src/qservkafka/config.py
- src/qservkafka/constants.py
- src/qservkafka/factory.py
- src/qservkafka/models/gafaelfawr.py
- src/qservkafka/models/kafka.py
- src/qservkafka/services/monitor.py
- src/qservkafka/services/query.py
- src/qservkafka/services/results.py
- src/qservkafka/storage/gafaelfawr.py
- src/qservkafka/storage/rate.py
- tests/conftest.py
- tests/data/status/data-overquota.json
- tests/data/status/simple-failed.json
- tests/kafka/query_test.py
- tests/services/monitor_test.py
- tests/storage/gafaelfawr_test.py
- tests/storage/rate_test.py
- tests/support/data.py
- tests/support/gafaelfawr.py
- tox.ini
- uv.lock
Add a caching Gafaelfawr client and associated configuration to retrieve the user's TAP quota for the configured TAP service name, if it exists. Add tracking of the number of concurrent queries each user has in progress. Using that information, impose a limit on concurrent queries if the user's TAP quota indicates there should be one, rejecting additional queries with an error until some other query completes.
Add a background reconcile job that updates the counts of running queries for each user based on a snapshot of other data stored in Redis. This works from a snapshot without a concurrency lock, so it may set the counts incorrectly, but it ensures that the system will self-heal against any problem (server crashes, for instance) that cause a failure to decrement the number of running …
> DM-51818: Add support for TAP query quotas

- changelog.d/20250721_144711_rra_DM_51889.md
- src/qservkafka/events.py
- src/qservkafka/services/query.py
- src/qservkafka/services/results.py
Add the TAP query ID to all metrics events to make it easier to correlate metrics events with specific queries.
> DM-51889: Add TAP query ID to metrics events

- changelog.d/20250721_153024_rra_DM_51889.md
- src/qservkafka/events.py
- src/qservkafka/models/qserv.py
- src/qservkafka/services/query.py
- src/qservkafka/storage/qserv.py
Include the elapsed time required to upload the table to Qserv in metrics events for successful user table uploads. This does not include the time required to retrieve the table from its source URLs before upload.
> DM-51889: Include elapsed time in table upload metrics events

- changelog.d/20250718_184044_steliosvoutsinas_DM_51834.md
- src/qservkafka/models/votable.py
- src/qservkafka/services/query.py
- src/qservkafka/storage/votable.py
- tests/models/votable_test.py
- tests/services/errors_test.py
- tests/storage/votable_test.py
Changes to support encoding `unicodeChar` in the binary2 encoder.
The motivation for this is that astropy as it is currently will set the type for string fields (uploaded as CSV) to `unicodeChar`.
This leads to an inconsistency between what our TAP service advertises as the datatype for the field (char) and what the uploaded table from Astropy has (`unicodeChar`).
The following notebook reproduces the problem:
https://github.com/lsst/cst-dev/blob/main/MLG_sandbox/DP1/300_Science_Demos/306_Extragalactic_transients/ut_fail_string_column.ipynb
- Added a couple of unit tests
- Tested running an TAP Upload query with the csv data from the above notebook which now completes successfully.
- I've also ran taplint via https://github.com/stvoutsin/rspvalidator and this completes successfully …
> DM-51834: Add support for unicodeChar fields in the binary2 encoding

- src/qservkafka/factory.py
- src/qservkafka/models/state.py
- src/qservkafka/services/monitor.py
- src/qservkafka/services/query.py
- src/qservkafka/services/results.py
- src/qservkafka/storage/state.py
- src/qservkafka/workers/functions/results.py
- tests/kafka/query_test.py
Create a new `Query` model that represents a query without a Qserv status, and rename the existing `Query` model to `RunningQuery`. The latter is what's stored in Redis. Simplify a bunch of APIs to take these models as arguments instead of a bunch of individual parameters.
> DM-51603: Use internal models to simplify APIs

- src/qservkafka/models/kafka.py
- src/qservkafka/models/state.py
- src/qservkafka/services/results.py
Rather than an additional constructor for `JobQueryInfo`, now that we're using the `RunningQuery` model everywhere, add a method on that object that builds the `JobQueryInfo` model directly.
> DM-51603: Simplify helper to create JobQueryInfo

- src/qservkafka/factory.py
- tests/kafka/query_test.py
- tests/services/leak_test.py
- tests/services/query_test.py
- tests/support/qserv.py
Add a test that retried failures from the Qserv API log metrics events. Enable testing with simulated flaky Qserv for one of the end-to-end Kafka tests as well.
Fix an initialization problem that caused the testing of a flaky Qserv REST API to be disabled. Previously, back to the refactoring of the Qserv mock, only flaky SQL connections were being tested.
Fix data leakage from the memory leak test into subsequent tests by correctly using monkeypatch to change global state instead of setting it directly. Move the disabling of the mock metrics publisher into a test-specific fixture.
> DM-51603: Improve testing of flaky Qserv API

- changelog.d/20250728_175358_rra_DM_51603.md
- src/qservkafka/events.py
- src/qservkafka/storage/votable.py
- src/qservkafka/workers/main.py
- tests/kafka/query_test.py
- tests/services/query_test.py
- tests/support/arq.py
Found and fixed a bug in the `encoded_size` field of success metrics events. Previously it was counting encoded size before base64 encoding, rather than afterwards.
Reworked how to pass in test objects for arq worker functions to make it easier to test metrics events omitted by the result worker.
> DM-51603: Add tests for query success metrics events

- src/qservkafka/services/query.py
- tests/services/errors_test.py
Add a test for posting a metrics event when a query is started but then fails inside Qserv. Currently, the bridge does not post metrics events for queries that fail before they are started, since they may be syntax errors or other user issues.
> DM-51603: Add test for metrics events on query failure

- tests/kafka/leak_test.py
- tests/kafka/query_test.py
- tests/services/leak_test.py
- tests/support/kafka.py
Add a memory leak test using the full end-to-end application with a real Kafka server and arq's burst mode. The memory leak threshold for failing has not yet been tuned.
> DM-51603: Add memory leak test with Kafka

- changelog.d/20250730_220717_steliosvoutsinas_DM_52016.md
- src/qservkafka/services/results.py
- src/qservkafka/storage/qserv.py
- tests/kafka/query_test.py
- tests/services/query_test.py
- tests/support/qserv.py
We recently discussed a plan to modify the upload behaviour a bit to create a separate database for each user query to address certain issues with orphaned user databases in QServ not allowing new upload jobs to be run.
I have a PR on the TAP service to enable this by modifying the name of the database to include the job id here:
https://github.com/lsst-sqre/lsst-tap-service/pull/163
In this PR I've modified the `services/results.py` and `storage/qserv.py` modules to now delete the databases associated with an uploaded table rather than the table.
> Changed table upload process to delete user database instead of tables

- changelog.d/20250805_113449_danfuchs_HEAD.md
- pyproject.toml
- src/qservkafka/config.py
- src/qservkafka/factory.py
- src/qservkafka/workers/main.py
- tests/conftest.py
- uv.lock
Publish an [ArqQueueJobEvent](https://safir.lsst.io/user-guide/arq.html#per-job-metrics) with a `time_in_queue` field at the start of every job.
Uses the [Safir generic arq metrics](https://safir.lsst.io/user-guide/arq.html#per-job-metrics).
> DM-52053: Per-job generic arq metrics

- .github/workflows/ci.yaml
- .github/workflows/periodic-ci.yaml
- Dockerfile
- changelog.d/20250805_120152_danfuchs_HEAD.md
- pyproject.toml
- src/qservkafka/cli.py
- src/qservkafka/factory.py
- src/qservkafka/periodic_metrics.py
- src/qservkafka/workers/main.py
- uv.lock
Add a script for publishing an [ArqQueueStatsEvent](https://safir.lsst.io/api/safir.metrics.ArqQueueStatsEvent.html#safir.metrics.ArqQueueStatsEvent). This should be called periodically, probably by a Kubernetes `CronJob`.
Uses [Safir generic arq metrics](https://safir.lsst.io/user-guide/arq.html#periodic-metrics).
Related [Phalanx PR](https://github.com/lsst-sqre/phalanx/pull/5201)
~I don't see how the time-in-queue metric can ever be negative :grimacing: Whatever the reason, I'm pretty sure it needs to be changed in Safir rather than in this app instrumentation.~
Edit: this is because I didn't pass `microseconds=True` to [current_datetime](https://safir.lsst.io/api/safir.datetime.current_datetime.html#safir.datetime.current_datetime). I assumed that that that truncated microseconds, but …
> DM-52053: Arq periodic metrics

- tests/data/qserv/data-completed.json
- tests/data/qserv/data-executing.json
- tests/data/qserv/simple-completed.json
- tests/data/qserv/simple-failed.json
- tests/data/qserv/simple-large.json
- tests/data/qserv/simple-partial.json
- tests/data/qserv/upload-failed.json
- tests/kafka/leak_test.py
- tests/kafka/query_test.py
- tests/services/errors_test.py
- tests/services/monitor_test.py
- tests/support/data.py
- tests/support/qserv.py
In the test suite, move Qserv status objects to data files and add a new helper function to load those data files. This keeps all of the test data together so that it can be consistently updated by changing the data files. It also prepares for adding new data fields.
> DM-52122: Move Qserv status to data files for testing

- src/qservkafka/factory.py
- src/qservkafka/workers/main.py
Move arq metrics initialization out of `ProcessContext` so that they're not unnecessarily initialized in the frontend and into the arq worker startup. This requires a somewhat annoying workaround to not initialize metrics more than once for tests that call the worker multiple times in burst mode.
> DM-52122: Do not initialize arq metrics in the frontend

- changelog.d/20250808_113750_rra_DM_52122.md
- src/qservkafka/storage/qserv.py
Update to match the current Qserv REST API version, if the bridge is configured to send versions on requests.
> DM-52122: Request API version 47 instead of 43

- src/qservkafka/models/state.py
When adding Qserv query status information to the logging context, omit `qserv_size` if Qserv hasn't reported collecting any bytes. This is the common case for executing queries since we don't retrieve the byte count from running queries.
> DM-52122: Don't log qserv_size if it is zero

- changelog.d/20250822_124622_rra_DM_52277.md
- src/qservkafka/storage/qserv.py
- tests/support/qserv.py
Update collation for user tables to `utf8mb4_uca1400_ai_ci`, which uses a newer version of the Unicode standard.
> DM-52277: Update collation to utf8mb4_uca1400_ai_ci

- src/qservkafka/services/results.py
Qserv only tracks timings to the nearest integer, so log it as an integer to not claim a decimal point of false precision.
> DM-52277: Log qserv_elapsed as an integer

- src/qservkafka/dependencies/context.py
- src/qservkafka/factory.py
- src/qservkafka/storage/qserv.py
- src/qservkafka/workers/functions/results.py
- src/qservkafka/workers/main.py
- tests/conftest.py
- tests/kafka/leak_test.py
- tests/support/qserv.py
`async_scoped_session` via Safir creates a separate session for every asyncio task, which requires shutting down that session at the end of every task or the sessions are leaked. This appears to be the source of the memory leaks previously incorrectly blamed on aiojobs.
Since the Qserv Kafka bridge now uses short-lived worker tasks, stop managing sessions with `async_scoped_session` and instead pass an `async_sessionmaker` down into the storage layer and create a new context-scoped session for each database operation.
> DM-52282: Stop using async_scoped_session

- changelog.d/20250826_140246_rra_DM_52282b.md
- src/qservkafka/models/state.py
- src/qservkafka/services/query.py
- src/qservkafka/services/results.py
Stop mistakenly updating the `created` time each time the results processor polls Qserv for a new status and instead fix it immediately after creation of the query in Qserv (and before geting the query status for the first time).
> DM-52282: Fix query creation timing in metrics events

- changelog.d/20250827_141325_rra_DM_52282.md
- src/qservkafka/config.py
- src/qservkafka/constants.py
- src/qservkafka/factory.py
- src/qservkafka/handlers/kafka.py
Add a setting for the maximum amount of data the Kafka consumer will consume at a time and set the default so that we can consume a full batch of wide queries. Change the default batch concurrency to 10 from 20 because this seems to work more smoothly with Qserv.
Add a setting for the Redis connection pool size and increase the default to account for the batch size plus some overhead for the monitor job.
Change the default for worker jobs per result worker to 2, matching the Phalanx configuration, and note that increasing it is probably pointless.
Lower the Qserv database connection pool size to something more realistic given the level of concurrency the bridge uses.
> DM-52282: Add more tuning parameters and adjust settings
