lsst-sqre/qserv-kafka

pyproject.toml, src/qservkafka/models/kafka.py, tests/models/kafka_test.py, uv.lock
Add Pydantic models for the basic Kafka messages for starting a job and reporting job status, based on SQR-097.
=> DM-49755: Add models of Kafka messages

pyproject.toml, src/qservkafka/config.py, src/qservkafka/dependencies/context.py, src/qservkafka/handlers/kafka.py, src/qservkafka/main.py, tests/conftest.py, tests/handlers/kafka_test.py, tests/support/logging.py, tox.ini, uv.lock
Consume `JobRun` models from Kafka, bind a logger, and then just log the contents of the message. Set up a test framework using the FastStream support for test in-memory Kafka brokers after an extended failed attempt to get Kafka testcontainers to work.
=> DM-49755: Add a basic Kafka consumer and test infrastructure

README.md
Add some real overview documentation and a pointer to SQR-097.
=> DM-49993: Flesh out README

src/qservkafka/models/kafka.py, src/qservkafka/services/query.py, tests/data/jobs/tabledata.json, tests/services/query_test.py
If the incoming request asks for TABLEDATA serialization, reject it immediately with an error.
=> DM-50188: Reject requests for TABLEDATA serialization

src/qservkafka/handlers/kafka.py
Reset to the earliest message if there is no saved offset.
=> DM-50277: Set offset reset policy on consumer

src/qservkafka/services/query.py
In the log message saying that the results have been uploaded, include the count of rows.
=> DM-50410: Log total number of rows in result

tests/services/query_test.py, tests/support/qserv.py
Add support for delaying the PUT to the upload URL and test handling of an upload timeout.
=> DM-50410: Add test of upload timeout handling

CHANGELOG.md, Dockerfile
Prepare the initial alpha-test release. Update the version of uv used in `Dockerfile`.
=> DM-50481: Prepare 0.1.0 release

.pre-commit-config.yaml, CHANGELOG.md, Dockerfile, changelog.d/20250505_130839_rra_DM_50527.md, changelog.d/20250505_155326_rra_DM_50527a.md, changelog.d/20250507_180313_rra_DM_50728.md, changelog.d/20250508_174532_rra_DM_50728.md, changelog.d/20250512_155207_rra_DM_50728.md, scripts/install-dependency-packages.sh, uv.lock
Collect the change log for the 0.2.0 release. Update Python and pre-commit dependencies.
=> DM-50728: Prepare 0.2.0 release

CHANGELOG.md, Dockerfile, changelog.d/20250516_165313_rra_DM_50961.md, changelog.d/20250523_103635_rra_DM_51085.md, changelog.d/20250527_104458_rra_DM_51113.md
Collect change log for the 0.4.0 release. Update the version of uv used in Docker container builds.
=> DM-50964: Prepare 0.4.0 release

src/qservkafka/storage/qserv.py
Move retrieving of data for table upload into separate methods in preparation for adding retry decorators.
=> DM-51310: Refactor retrieval of table upload data

.pre-commit-config.yaml, CHANGELOG.md, Dockerfile, changelog.d/20250609_081648_rra_DM_51308.md, changelog.d/20250609_104115_rra_DM_51308.md, changelog.d/20250609_121639_rra_DM_51308.md, changelog.d/20250609_180548_rra_DM_51308.md, changelog.d/20250610_181601_rra_DM_51310.md, changelog.d/20250611_135402_rra_DM_51309.md, changelog.d/20250611_155153_rra_DM_51309.md, uv.lock
Collect the change log for release 0.6.0. Update pre-commit, Python, and Dockerfile uv dependencies.
=> DM-51358: Prepare release 0.6.0

src/qservkafka/storage/qserv.py
Move the adjustment of the httpx timeout to the right layer of the abstraction.
=> DM-51365: Fix timeout handling for table upload

CHANGELOG.md, changelog.d/20250627_123645_rra_DM_51594.md, uv.lock
Collect change log for the 1.0.1 release. Update Python dependencies.
=> DM-51594: Prepare 1.0.1 release

src/qservkafka/services/query.py
If the API call to create the query fails, assume that's a user problem rather than an API problem and log that only at an info level rather than with a full backtrace. Unfortunately, we can't do the same when getting the query status fails, since there's no way to distinguish between protocol failures (query doesn't exist) and Qserv errors (query results were too large).
=> DM-51603: Suppress backtrace when Qserv rejects query

src/qservkafka/models/state.py, src/qservkafka/services/monitor.py, src/qservkafka/services/results.py
Avoid some code duplication by adding a helper function to `Query` to return variables for a structlog logging context.
=> DM-51903: Add helper function to build logging contexts

.github/workflows/ci.yaml, .github/workflows/periodic-ci.yaml, .pre-commit-config.yaml, CHANGELOG.md, Dockerfile, changelog.d/20250718_184044_steliosvoutsinas_DM_51834.md, changelog.d/20250728_175358_rra_DM_51603.md, changelog.d/20250730_141256_rra_DM_51603a.md, scripts/update-uv-version.sh, src/qservkafka/background.py, uv.lock
Collect the change log for the 1.2.0 release. Update pre-commit and Python dependencies.
=> DM-51603: Prepare 1.2.0 release

src/qservkafka/storage/qserv.py
Stop interpolating the query ID directly into the SQL and instead use bind variables like a proper SQL client. This may also help with query cache usage.
=> DM-52282: Use bind variables to get query results

CHANGELOG.md, changelog.d/20250822_124622_rra_DM_52277.md, changelog.d/20250822_182459_rra_DM_52282.md, changelog.d/20250826_140246_rra_DM_52282b.md, changelog.d/20250827_141325_rra_DM_52282.md, changelog.d/20250827_143342_rra_DM_52282.md, uv.lock
Collect the change log for the 3.1.0 release. Update Python dependencies.
=> DM-52282: Prepare 3.1.0 release

.github/workflows/ci.yaml, .github/workflows/periodic-ci.yaml, .pre-commit-config.yaml, CHANGELOG.md, Dockerfile, changelog.d/20250923_063053_steliosvoutsinas_HEAD.md, changelog.d/20250923_063320_steliosvoutsinas_HEAD.md, uv.lock
Collect the change log for the 3.2.0 release and update dependencies.
=> DM-52401: Prepare 3.2.0 release
